### PR TITLE
Added ADI Labs Jr info

### PR DESCRIPTION
**Pull request by thebrianzeng**

### CODE REVIEW

**Comment by thebrianzeng** [comment]
screen shot 2015-02-11 at 10 23 45 pm
screen shot 2015-02-11 at 10 23 58 pm
screen shot 2015-02-11 at 10 24 05 pm
screen shot 2015-02-11 at 10 24 13 pm

**Comment by danrschlosser** [comment]
I think that "ADI Labs Jr" is kind of a baby-ish name.  Could we find a different name?

**Comment by thebrianzeng** [comment]
yeah i didn't put any effort into that name - any suggestions?

**Comment by danrschlosser** [comment]
ADI Labs Experiments
ADI Starter Labs
ADI First Labs
ADI Labs Zero

**Comment by danrschlosser** [comment]
Or we could merge it and call it all ADI Labs and just make the distinction internally

**Comment by thebrianzeng** [comment]
i like ADI Starter Labs or ADI Labs Zero. i think a distinction would help
people just to help people understand it when they hear about it - and
might make people feel more comfortable?

**Pull request closed without merging**
